/**
 * InspectVoice — Public Verification Page
 * /verify/:bundleId — no login required
 *
 * Shows a tamper-evidence receipt: status, document type, date,
 * SHA-256 fingerprint. Designed for council officers, solicitors,
 * and insurers to validate exported documents.
 *
 * Calls GET /api/v1/verify/:bundleId (public endpoint, no JWT).
 *
 * Build Standard: Autaimate v3 — TypeScript strict, zero any, production-ready
 */

import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Shield, ShieldCheck, ShieldX, Clock, FileText, Hash, Loader2, AlertTriangle } from 'lucide-react';

// =============================================
// TYPES
// =============================================

interface VerificationSuccess {
  readonly valid: true;
  readonly bundle_id: string;
  readonly export_type: string;
  readonly generated_at: string;
  readonly file_count: number;
  readonly signature_algorithm: string;
  readonly signing_key_id: string;
  readonly manifest_sha256: string;
}

interface VerificationFailure {
  readonly valid: false;
  readonly reason: string;
}

type VerificationResult = VerificationSuccess | VerificationFailure;

type LoadState = 'loading' | 'success' | 'invalid' | 'not_found' | 'error';

// =============================================
// CONSTANTS
// =============================================

const EXPORT_TYPE_LABELS: Record<string, string> = {
  defect_export: 'Defect Export Report',
  pdf_report: 'Inspection PDF Report',
  claims_pack: 'Incident Claims Pack',
};

const API_BASE = import.meta.env.VITE_API_BASE_URL as string;

// =============================================
// COMPONENT
// =============================================

export default function VerifyPage() {
  const { bundleId } = useParams<{ bundleId: string }>();
  const [state, setState] = useState<LoadState>('loading');
  const [result, setResult] = useState<VerificationResult | null>(null);

  useEffect(() => {
    if (!bundleId) {
      setState('invalid');
      return;
    }

    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(bundleId)) {
      setState('invalid');
      return;
    }

    let cancelled = false;

    async function verify() {
      try {
        const response = await fetch(`${API_BASE}/api/v1/verify/${bundleId}`, {
          method: 'GET',
          headers: { 'Accept': 'application/json' },
        });

        if (cancelled) return;

        const data = (await response.json()) as VerificationResult;
        setResult(data);

        if (data.valid) {
          setState('success');
        } else if (response.status === 404) {
          setState('not_found');
        } else {
          setState('invalid');
        }
      } catch {
        if (!cancelled) setState('error');
      }
    }

    verify();
    return () => { cancelled = true; };
  }, [bundleId]);

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 py-4 px-6">
        <div className="max-w-2xl mx-auto flex items-center gap-3">
          <Shield className="w-7 h-7 text-emerald-600" />
          <div>
            <h1 className="text-lg font-semibold text-slate-900">InspectVoice</h1>
            <p className="text-xs text-slate-500">Document Verification Service</p>
          </div>
        </div>
      </header>

      {/* Main */}
      <main className="flex-1 flex items-start justify-center px-4 py-12">
        <div className="w-full max-w-2xl">
          {state === 'loading' && <LoadingCard />}
          {state === 'success' && result && result.valid && <SuccessCard data={result} />}
          {state === 'not_found' && <NotFoundCard />}
          {state === 'invalid' && result && !result.valid && <InvalidCard reason={result.reason} />}
          {state === 'invalid' && !result && <InvalidCard reason="Invalid bundle ID format" />}
          {state === 'error' && <ErrorCard />}
        </div>
      </main>

      {/* Footer */}
      <footer className="py-6 px-4 text-center text-xs text-slate-400">
        <p>This verification confirms the document was generated by InspectVoice and has not been modified since export.</p>
        <p className="mt-1">© {new Date().getFullYear()} Autaimate Ltd. All rights reserved.</p>
      </footer>
    </div>
  );
}

// =============================================
// SUB-COMPONENTS
// =============================================

function LoadingCard() {
  return (
    <div className="bg-white rounded-lg border border-slate-200 p-10 text-center">
      <Loader2 className="w-10 h-10 text-slate-400 animate-spin mx-auto" />
      <p className="mt-4 text-sm text-slate-500">Verifying document integrity…</p>
    </div>
  );
}

function SuccessCard({ data }: { readonly data: VerificationSuccess }) {
  const exportLabel = EXPORT_TYPE_LABELS[data.export_type] ?? data.export_type;
  const generatedDate = new Date(data.generated_at);
  const formattedDate = generatedDate.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
  const formattedTime = generatedDate.toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <div className="bg-white rounded-lg border border-emerald-200 overflow-hidden">
      {/* Status banner */}
      <div className="bg-emerald-50 border-b border-emerald-200 px-6 py-5 flex items-center gap-4">
        <div className="bg-emerald-100 rounded-full p-3">
          <ShieldCheck className="w-8 h-8 text-emerald-600" />
        </div>
        <div>
          <h2 className="text-lg font-semibold text-emerald-900">Document Verified</h2>
          <p className="text-sm text-emerald-700">This document is authentic and has not been tampered with.</p>
        </div>
      </div>

      {/* Details */}
      <div className="px-6 py-5 space-y-4">
        <DetailRow
          icon={<FileText className="w-4 h-4 text-slate-400" />}
          label="Document Type"
          value={exportLabel}
        />
        <DetailRow
          icon={<Clock className="w-4 h-4 text-slate-400" />}
          label="Generated"
          value={`${formattedDate} at ${formattedTime}`}
        />
        <DetailRow
          icon={<FileText className="w-4 h-4 text-slate-400" />}
          label="Files in Bundle"
          value={String(data.file_count)}
        />
        <DetailRow
          icon={<Shield className="w-4 h-4 text-slate-400" />}
          label="Signature Algorithm"
          value={data.signature_algorithm}
        />

        {/* SHA-256 fingerprint — full width, monospace */}
        <div className="pt-2 border-t border-slate-100">
          <div className="flex items-center gap-2 mb-2">
            <Hash className="w-4 h-4 text-slate-400" />
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wide">SHA-256 Fingerprint</span>
          </div>
          <div className="bg-slate-50 border border-slate-200 rounded px-3 py-2">
            <code className="text-xs text-slate-700 font-mono break-all leading-relaxed">
              {data.manifest_sha256}
            </code>
          </div>
        </div>

        {/* Bundle reference */}
        <div className="pt-2 border-t border-slate-100">
          <div className="flex items-center gap-2 mb-2">
            <FileText className="w-4 h-4 text-slate-400" />
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wide">Bundle Reference</span>
          </div>
          <code className="text-xs text-slate-600 font-mono">{data.bundle_id}</code>
        </div>
      </div>

      {/* Verification timestamp */}
      <div className="bg-slate-50 border-t border-slate-200 px-6 py-3">
        <p className="text-xs text-slate-400">
          Verified at {new Date().toLocaleString('en-GB')} — This result confirms the document
          was generated by InspectVoice and the content hash matches the original export.
        </p>
      </div>
    </div>
  );
}

function NotFoundCard() {
  return (
    <div className="bg-white rounded-lg border border-amber-200 overflow-hidden">
      <div className="bg-amber-50 border-b border-amber-200 px-6 py-5 flex items-center gap-4">
        <div className="bg-amber-100 rounded-full p-3">
          <AlertTriangle className="w-8 h-8 text-amber-600" />
        </div>
        <div>
          <h2 className="text-lg font-semibold text-amber-900">Bundle Not Found</h2>
          <p className="text-sm text-amber-700">
            No sealed export matches this reference. The bundle may have been revoked or the ID may be incorrect.
          </p>
        </div>
      </div>
      <div className="px-6 py-4">
        <p className="text-sm text-slate-600">
          If you believe this is an error, contact the organisation that issued the document
          or email <span className="font-medium">support@autaimate.com</span> for assistance.
        </p>
      </div>
    </div>
  );
}

function InvalidCard({ reason }: { readonly reason: string }) {
  return (
    <div className="bg-white rounded-lg border border-red-200 overflow-hidden">
      <div className="bg-red-50 border-b border-red-200 px-6 py-5 flex items-center gap-4">
        <div className="bg-red-100 rounded-full p-3">
          <ShieldX className="w-8 h-8 text-red-600" />
        </div>
        <div>
          <h2 className="text-lg font-semibold text-red-900">Verification Failed</h2>
          <p className="text-sm text-red-700">{reason}</p>
        </div>
      </div>
      <div className="px-6 py-4">
        <p className="text-sm text-slate-600">
          This document could not be verified. It may have been modified after export, or the
          verification link may be invalid. Contact the issuing organisation for a fresh copy.
        </p>
      </div>
    </div>
  );
}

function ErrorCard() {
  return (
    <div className="bg-white rounded-lg border border-slate-200 p-8 text-center">
      <AlertTriangle className="w-10 h-10 text-slate-400 mx-auto" />
      <h2 className="mt-4 text-base font-semibold text-slate-900">Service Unavailable</h2>
      <p className="mt-2 text-sm text-slate-500">
        The verification service is temporarily unavailable. Please try again shortly.
      </p>
    </div>
  );
}

function DetailRow({
  icon,
  label,
  value,
}: {
  readonly icon: React.ReactNode;
  readonly label: string;
  readonly value: string;
}) {
  return (
    <div className="flex items-start gap-3">
      <div className="mt-0.5">{icon}</div>
      <div>
        <p className="text-xs font-medium text-slate-500 uppercase tracking-wide">{label}</p>
        <p className="text-sm text-slate-900 mt-0.5">{value}</p>
      </div>
    </div>
  );
}
