/**
 * InspectVoice — Application Entry Point
 *
 * Responsibilities:
 *   1. Initialise observability (Sentry, analytics) before React renders
 *   2. Register the PWA service worker (generated by vite-plugin-pwa)
 *   3. Wrap the app in ClerkProvider for authentication
 *   4. Mount the React application
 *
 * Note: BrowserRouter and HelmetProvider are in App.tsx — NOT duplicated here.
 *
 * Build Standard: Autaimate v3
 */

import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { ClerkProvider } from '@clerk/clerk-react';
import { registerSW } from 'virtual:pwa-register';
import { initErrorTracking } from '@utils/errorTracking';
import { initAnalytics } from '@utils/analytics';
import { App } from './App';
import './index.css';

// =============================================
// 0. CLERK — validate publishable key
// =============================================

const CLERK_PUBLISHABLE_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY as string | undefined;

if (!CLERK_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing VITE_CLERK_PUBLISHABLE_KEY environment variable. ' +
    'Set it in Railway and redeploy (Vite bakes env vars at build time).'
  );
}

// =============================================
// 1. OBSERVABILITY — before React renders
// =============================================

initErrorTracking();
initAnalytics({ debug: !import.meta.env.PROD });

// =============================================
// 2. PWA SERVICE WORKER REGISTRATION
// =============================================

/**
 * Register the Workbox service worker.
 *
 * registerType: 'prompt' in vite.config.ts means the SW won't
 * auto-activate on update — instead we store the updateSW callback
 * on window so the PWAUpdatePrompt component can trigger it when
 * the user accepts.
 *
 * Flow:
 *   1. New SW detected → onNeedRefresh fires
 *   2. PWAUpdatePrompt component shows banner
 *   3. User clicks "Update" → calls window.__IV_SW_UPDATE(true)
 *   4. New SW activates, page reloads
 */
const updateSW = registerSW({
  onNeedRefresh() {
    window.dispatchEvent(new CustomEvent('iv-sw-update-available'));
  },
  onOfflineReady() {
    window.dispatchEvent(new CustomEvent('iv-sw-offline-ready'));
  },
  onRegisteredSW(swUrl, registration) {
    if (registration) {
      setInterval(() => {
        void registration.update();
      }, 60 * 60 * 1000);
    }
    if (import.meta.env.DEV) {
      console.info('[PWA] Service worker registered:', swUrl);
    }
  },
  onRegisterError(error) {
    console.error('[PWA] Service worker registration failed:', error);
  },
});

declare global {
  interface Window {
    __IV_SW_UPDATE?: (reloadPage: boolean) => Promise<void>;
  }
}
window.__IV_SW_UPDATE = updateSW;

// =============================================
// 3. MOUNT REACT APP
// =============================================

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error('Root element not found. Check index.html has <div id="root">.');
}

createRoot(rootElement).render(
  <StrictMode>
    <ClerkProvider publishableKey={CLERK_PUBLISHABLE_KEY}>
      <App />
    </ClerkProvider>
  </StrictMode>,
);
